version: "3.8"
services:
  mssql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: sql_server
    hostname: sql_server
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong@Password123" # !! Dein Passwort!!
    ports:
      - "1433:1433"
    volumes:
      - sql_data_volume:/var/opt/mssql
    restart: unless-stopped
volumes:
  sql_data_volume: {}
